#!/usr/bin/env bash
set -euo pipefail

mkdir -p projects
cat > projects/projects.md <<'INDEX'
# Projects index

_This file is autogenerated by .github/workflows/update-projects.yml_

Found Rust projects:

INDEX

# Find Cargo.toml files, derive directory and optional description
while IFS= read -r -d $'\0' file; do
  dir=$(dirname "$file")
  dir=$(echo "$dir" | sed 's:/*$::' | sed 's|^\./||')
  desc=$(awk -F'=' '/^description[ \t]*=/{gsub(/^ +| +$/,"",$2); gsub(/^"|"$/,"",$2); print $2; exit}' "$dir/Cargo.toml" 2>/dev/null || true)
  if [ -z "$desc" ]; then desc="Rust project"; fi
  echo "- [${dir}](${dir}) - ${desc}" >> projects/projects.md
done < <(find . -type f -name Cargo.toml -not -path './target/*' -not -path './.github/*' -print0 | sort -z)

echo "Generated projects/projects.md"
