name: Update projects index

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate projects index
        shell: bash
        run: |
          ./.github/scripts/generate_projects.sh

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git status --porcelain | grep -q 'projects/projects.md'; then
            git add projects/projects.md
            git commit -m "chore: update projects index"
            git push
          else
            echo "No changes to commit"
          fi
